version: "3.8"
services:
  mysql:
    image: mysql:5.7.32
    container_name: mysql-container
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/schemas:/docker-entrypoint-initdb.d
      - .:/app
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pass
